[package]
name = "scurry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.1"
clap = { version = "4.0.13", features = ["derive"] }
rustyline = "10.0.0"
thiserror = "1.0.37"
