name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Scurry
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust 1.65.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.65.0
          override: true

      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
